<a href="https://colab.research.google.com/github/crisbpadilla/DataScience-M2M-course-Datatalent/blob/main/ArrayExcercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook serve as a note for excersices done along the course.

Creating arrays with diferent dimension:

---

a.-(3,2) array
b.-(2,4)
c.-(2,1)
d.-(2,1,2)

In [2]:
import numpy as np

a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
c=np.array([[1],[2]])
print(c.shape)
print(c)

(2, 1)
[[1]
 [2]]


In [7]:
d=np.array([[[2,1]],[[2,1]]])
print(f'This array has dimension {d.ndim} , shape {d.shape} and the array is represented with the next vector {d}')

This array has dimension3 , shape (2, 1, 2) and the array is represented with the next vector [[[2 1]]

 [[2 1]]]


In [14]:
import numpy as np

a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[1,2,3,4],[5,6,7,8]])
c=np.array([[1],[2]])
d=np.array([[[2,1]],[[2,1]]])

ex=np.array([a,b,c,d],dtype=object)

for arrays in ex:
 print(f'This array has dimension {arrays.ndim} , shape {arrays.shape} and the array is represented with the next vector {arrays}')

This array has dimension 2 , shape (3, 2) and the array is represented with the next vector [[1 2]
 [3 4]
 [5 6]]
This array has dimension 2 , shape (2, 4) and the array is represented with the next vector [[1 2 3 4]
 [5 6 7 8]]
This array has dimension 2 , shape (2, 1) and the array is represented with the next vector [[1]
 [2]]
This array has dimension 3 , shape (2, 1, 2) and the array is represented with the next vector [[[2 1]]

 [[2 1]]]


For the iteration made before we also can use the python function 'list()' instead of using the array function of the numpy library.

In [15]:
import numpy as np

a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[1,2,3,4],[5,6,7,8]])
c=np.array([[1],[2]])
d=np.array([[[2,1]],[[2,1]]])

ex=list([a,b,c,d])

for arrays in ex:
 print(f'This array has dimension {arrays.ndim} , shape {arrays.shape} and the array is represented with the next vector {arrays}')

This array has dimension 2 , shape (3, 2) and the array is represented with the next vector [[1 2]
 [3 4]
 [5 6]]
This array has dimension 2 , shape (2, 4) and the array is represented with the next vector [[1 2 3 4]
 [5 6 7 8]]
This array has dimension 2 , shape (2, 1) and the array is represented with the next vector [[1]
 [2]]
This array has dimension 3 , shape (2, 1, 2) and the array is represented with the next vector [[[2 1]]

 [[2 1]]]


Challenge 2, Create a new array of ones of shape (5,5) and index into it in such a way that the result is an arrange of shape (2,3)


In [23]:
a1= np.ones((5,5), dtype=int)# create my array of ones of dimension 5,5
print(a1[0:2,2:5])
print(a1[1:3,0:3])

[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]]


Challenge 3, create an empty array of shape (3,3,3) and iterate in the elements in two different ways


In [7]:
import numpy as np
# first we proceed with the creation of the array
ea=np.empty((3,3,3), dtype=int)
print(ea)
#now I can iterate the elements of this array in two ways, using the numpy function flat, or iterating within the elements of any axis

#iterating within the dimensions
for row in ea:
  for col in row:
    for el in col:
      print(el)

#using the flat function

for el in ea.flat:
  print(el)

[[[ 94148874073277               0 135456223267952]
  [135456441246864 135456442743152 135456442743152]
  [135456225009728 135456440399472 135456441246864]]

 [[135456440399472 135456440399472 135456225004496]
  [135456436323440 135456441475280 135456436323440]
  [135456436323440 135456442122288 135456442743472]]

 [[135456442743472 135456442743472 135456442743472]
  [135456442743152 135456442743472 135456442122288]
  [135456442122288 135456441122544             416]]]
94148874073277
0
135456223267952
135456441246864
135456442743152
135456442743152
135456225009728
135456440399472
135456441246864
135456440399472
135456440399472
135456225004496
135456436323440
135456441475280
135456436323440
135456436323440
135456442122288
135456442743472
135456442743472
135456442743472
135456442743472
135456442743152
135456442743472
135456442122288
135456442122288
135456441122544
416
94148874073277
0
135456223267952
135456441246864
135456442743152
135456442743152
135456225009728
135456440399472
13545644

Reshaping an array with reshape((shape wanted as tuple)) function

First challenge on reshaping. create an array with numbers from 0 to 50 with 10 rows and 5 columns

In [10]:
import numpy as np

a2=np.arange(0,50)
ra2=a2.reshape((10,5))
print(a2)
print(ra2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


Create an array of shape (5,6,7) updated to be flatted and then back to its previous shape. Finally explain the shape of the array.

In [9]:
import numpy as np

a3=np.arange(5*6*7)
ash=a3.reshape(5,6,7)
# Or i could create directly an array using the method zero, ones or empty with
# the determined shape
a4=np.ones((5,6,7))

print (a4)
print(a4.ravel())
print(ash)
print(ash.ravel())
# the shape of the current array  has  5 set of arrays or list of data, in which
# within any one of them you have an set of data displayed as an array of shape
# (6,7), so it has 6 rows and 7 columns. being like [a,b,c,d,e] where a=b=c=d=e=
# np.ones((6,7))

[[[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1.

Challenge:
1.- Create an array with values ranging from 1 to 30 in two different ways
2.-reshape te arrays to have shape (3,10)
3.-Split the array in 3 different parts in any way you want.
4.-join the arrays part back togheter to get back the array of shape (3,10)

In [21]:
import numpy as np
#create the array
#first way using arange
arr=np.arange(1,31)
# sercond way using the method r_
arr2=np.r_[1:31]
#or a third way using the method C_ and hstack
arr3=np.hstack((np.c_[1:31]))

#reshaping the arrays arr1 and arr2

arrA= arr.reshape((3,10))
arrB= arr2.reshape((3,10))

#Splittiing the array in 3 different parts

Sarr=np.vsplit(arrA,3)

#get back the array shape (3,10)

Rarr=np.ravel(Sarr).reshape((3,10))

print(arr)
print(arrA)
print(Sarr)
print(f'The array Sarr is reshape to {Rarr}')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]]), array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])]
The array Sarr is reshape to [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
