<a href="https://colab.research.google.com/github/crisbpadilla/DataScience-M2M-course-Datatalent/blob/main/ChallengesNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook serve as a note for excersices done along the course.

Creating arrays with diferent dimension:

---

a.-(3,2) array
b.-(2,4)
c.-(2,1)
d.-(2,1,2)

In [2]:
import numpy as np

a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
c=np.array([[1],[2]])
print(c.shape)
print(c)

(2, 1)
[[1]
 [2]]


In [7]:
d=np.array([[[2,1]],[[2,1]]])
print(f'This array has dimension {d.ndim} , shape {d.shape} and the array is represented with the next vector {d}')

This array has dimension3 , shape (2, 1, 2) and the array is represented with the next vector [[[2 1]]

 [[2 1]]]


In [14]:
import numpy as np

a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[1,2,3,4],[5,6,7,8]])
c=np.array([[1],[2]])
d=np.array([[[2,1]],[[2,1]]])

ex=np.array([a,b,c,d],dtype=object)

for arrays in ex:
 print(f'This array has dimension {arrays.ndim} , shape {arrays.shape} and the array is represented with the next vector {arrays}')

This array has dimension 2 , shape (3, 2) and the array is represented with the next vector [[1 2]
 [3 4]
 [5 6]]
This array has dimension 2 , shape (2, 4) and the array is represented with the next vector [[1 2 3 4]
 [5 6 7 8]]
This array has dimension 2 , shape (2, 1) and the array is represented with the next vector [[1]
 [2]]
This array has dimension 3 , shape (2, 1, 2) and the array is represented with the next vector [[[2 1]]

 [[2 1]]]


For the iteration made before we also can use the python function 'list()' instead of using the array function of the numpy library.

In [15]:
import numpy as np

a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[1,2,3,4],[5,6,7,8]])
c=np.array([[1],[2]])
d=np.array([[[2,1]],[[2,1]]])

ex=list([a,b,c,d])

for arrays in ex:
 print(f'This array has dimension {arrays.ndim} , shape {arrays.shape} and the array is represented with the next vector {arrays}')

This array has dimension 2 , shape (3, 2) and the array is represented with the next vector [[1 2]
 [3 4]
 [5 6]]
This array has dimension 2 , shape (2, 4) and the array is represented with the next vector [[1 2 3 4]
 [5 6 7 8]]
This array has dimension 2 , shape (2, 1) and the array is represented with the next vector [[1]
 [2]]
This array has dimension 3 , shape (2, 1, 2) and the array is represented with the next vector [[[2 1]]

 [[2 1]]]
